### ISSUE TITLE
unlisted dependency

### ISSUE THREAD

**Issue by dchmelik** [Buzztrax/buzztrax#112]
```
d@1.cosmos:~$ buzztrax-edit
buzztrax-edit: error while loading shared libraries: libbuzztrax-gst.so.1: cannot open shared object file: No such file or directory
```

**Comment by ensonic** [comment]
configure installs by default to "/usr/local". Did you configure your system for that? (see https://github.com/Buzztrax/buzztrax/blob/master/README.md#installing-locally)

To verify:
```
> echo $LD_LIBRARY_PATH
> which buzztrax-edit
> ldd $(which buzztrax-edit)
# if you see error loading libraries, then probably /usr/local/lib is not part of your $LD_LIBRARY_PATH
```

**Comment by dchmelik** [comment]
The main problem is build/installation instructions aren't well-described except somewhat for expert programmers who have already done similar process many times.  LIke last time, after days/weeks trying I got it installed again
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I installed to /usr/local/lib64 (except stuff that looks like user configuration) but once again but again no extra buzzmachines (after installing those).

**Comment by ensonic** [comment]
I can't replicate Autotools docs in my Readme. The default settings are
unfortunate, so if you don't want to reconfigure your system for source
installs, simply use --prefix=/usr

David Chmelik ***@***.***> schrieb am Mo., 25. Juli 2022,
19:28:
