### ISSUE TITLE
Memory leak on save?

### ISSUE THREAD

**Issue by dlbeswick** [Buzztrax/buzztrax#115]
As far as I could see,  it looks liek "xmlDocFree" isn't being used in the song save function to free the XML generated on save. Is there a memory leak here, or did I miss something?

**Comment by ensonic** [comment]
Does valgrind show one? What are you seeing?

**Comment by ensonic** [comment]
That makes sense. I think we can merge both together.

**Comment by ensonic** [comment]
This we can now close, right?
