### ISSUE TITLE
migrate ci-setup to github-actions

### ISSUE THREAD

**Issue by ensonic** [Buzztrax/buzztrax#126]
We used Travic-Ci in the past (see .travis.yml in the repos). 2 Options:

1. Apply for a free open source project plan at travis
1. Go though https://docs.github.com/en/actions/migrating-to-github-actions/manually-migrating-to-github-actions/migrating-from-travis-ci-to-github-actions

**Comment by ensonic** [comment]
Thank would be awesome!

**Comment by rffontenelle** [comment]
Great! So, just some preliminar questions before I start working on it:
- README's build statements are up-to-date(/-ish)? Should I base the build steps on it?
- Any definition on distros and architectures to build on? Most common is ubuntu-latest (22.04 right now, x86_64), but it is possible to set other distro and scenarios too.

**Comment by ensonic** [comment]
Yep, the README is up-to-date. If you bump into any build issues, happy to help. I personally work with both debian-testing and opensuse tumbleweed, but using a ubuntu base should be fine too.

**Comment by ensonic** [comment]
FYI: I discovered https://github.com/nektos/act which lets me runs those locally, hopefully I can figure out what prevents the UI tests to run.
