### ISSUE TITLE
Add interpolate function to Pattern Editor a-la Buzz

### ISSUE THREAD

**Issue by dlbeswick** [Buzztrax/buzztrax#131]
Along the lines of #130 , in Buzz CTRL + I interpolates the values linearly from the start and end of the selection in the pattern editor.

* Any column being interpolated must have a value defined for both the start and end of the selection.
* If multiple columns are selected, then it could be applied to any column in the selection meeting the prerequisites.
* There's probably no point interpolating note columns.
* Maybe Buzztrax could do something cooler, like popping up a dialog allowing different interpolations besides linear, or "drawing" values down a column with the mouse.

**Comment by ensonic** [comment]
Just verified, but Ctrl-I is already implemented.
https://github.com/Buzztrax/buzztrax/blob/master/src/ui/edit/main-page-patterns.c#L26
