### ISSUE TITLE
Handle invalid presets

### ISSUE THREAD

**Issue by ensonic** [Buzztrax/buzztrax#48]
Preset might get corrupted or one might load a preset saved for a different version. While this should be all handled with versioning, it might be a good idea to do a two pass load, first check the ranges and then only load if all ranges are good. This avoid tons of glib warnings like
   
    (buzztrax-edit:32585): GLib-GObject-WARNING **: value "((bml-FSM-InfectorOSC2-Wave) 106)" of type 'bml-FSM-InfectorOSC2-Wave' is invalid or out of range for property 'OSC2-Wave' of type 'bml-FSM-InfectorOSC2-Wave'

**Comment by Gimmeapill** [comment]
Same issue with Makk-M4: it bails out instantly when trying to load any of the default presets
