### ISSUE TITLE
Scroll Wheel in Pattern Editor

### ISSUE THREAD

**Issue by Gimmeapill** [Buzztrax/buzztrax#54]
Not sure if it's a bug or feature request: In Buzztrax it doesn't seem to be possible to navigate to the bottom of long patterns that do not fit on the screen vertically (ex: 64 steps on my 1280x800). In old Buzz, this is achievable with the cursor, page up/down or the scroll wheel (this is one of the feature brought by Overloader).

**Comment by Gimmeapill** [comment]
Forgot to mention: I'm using Flubox WM and didn't test on Gnome recently.

**Comment by ensonic** [comment]
There is one regression from porting to gtk+3 - the widget does not scroll to keep the cursor visible. I'll take a look.
