### ISSUE TITLE
gcc 5.1.1: can't convert between vector values of different size

### ISSUE THREAD

**Issue by awissu** [Buzztrax/buzztrax#57]
If include file xmmintrin.h compilation fails  with the following message:

[  184s] /usr/lib/gcc/i586-suse-linux/5/include/mmintrin.h:64:3: error: can't convert between vector values of different size
[  184s]    return (__m64) __builtin_ia32_vec_init_v2si (__i, 0);

See the logfile for details: https://pmbs.links2linux.de/package/live_build_log/home:awissu:branches:Extra/buzztrax/openSUSE_Tumbleweed/i586

**Comment by ensonic** [comment]
Isn't that a problem with the mmintrin.h header itself? I am only calling

    _mm_setcsr (_mm_getcsr () | 0x8040);

and not any of the code that is causing these errors.

**Comment by awissu** [comment]
Fix build with gcc5 on x86: add -msse in the command line

**Comment by ensonic** [comment]
Thanks, I'll check how to add this in a portable way to configure.

**Comment by ensonic** [comment]
I have a patch here: https://gist.github.com/ensonic/e9158ec4c5ef8d032444, needs a bit of testing

**Comment by sdroege** [comment]
Builds fine now, thanks!

**Comment by ensonic** [comment]
@awissu btw. GLIB=2.32.0 should be enough.
