### ISSUE TITLE
0.10.1 does not build with GStreamer < 1.6

### ISSUE THREAD

**Issue by sdroege** [Buzztrax/buzztrax#58]
Fixed with this here: https://anonscm.debian.org/cgit/pkg-gstreamer/buzztrax.git/plain/debian/patches/0001-Fix-compilation-with-GStreamer-1.6.patch

**Comment by ensonic** [comment]
Thanks, pushed to both master and BRANCH_0_10.

**Comment by Gimmeapill** [comment]
Looks like I was affected as well - thx for fixing ;-)
