### ISSUE TITLE
src/lib/gst/audiosynth.* has no copyright information

### ISSUE THREAD

**Issue by sdroege** [Buzztrax/buzztrax#59]

**Comment by ensonic** [comment]
Not sure what you mean:
https://github.com/Buzztrax/buzztrax/blob/master/src/lib/gst/audiosynth.c#L5-L16
https://github.com/Buzztrax/buzztrax/blob/master/src/lib/gst/audiosynth.h#L3-L14

**Comment by sdroege** [comment]
Compare to https://github.com/Buzztrax/buzztrax/blob/master/src/lib/gst/childbin.c#L2 :)

For the Debian package I assumed it to be the same as most of the other files in that directory.

**Comment by ensonic** [comment]
Now, I get it - Copyright, not license. Yes, it is the same for all the files. I'll add this right away.
