### ISSUE TITLE
A translation string stated as "development version (do not translate this)"

### ISSUE THREAD

**Issue by josephgbr** [Buzztrax/buzztrax#66]
Hello,

Maybe this is more a doubt than a bug.  I just started translating buzztrax to pt_BR and I notice the following string:

> #. "Development version (do not translate this)"
#.
#: ../src/ui/edit/about-dialog.c:117
msgid ""
"Just a few month since the previous release, this update mostly focuses on "
"getting rid of deprecated APIs. Besides that it also come with a new "
"synthesizer plugin called 'ebeats'. As the name suggests it is good at "
"making percussion sounds. Together with that the library providing the dsp "
"components got overhauled."
msgstr ""

So, just to be sure: Should I keep this message in English?   If yes, please consider hidding it from PO file, as it might confuse the translator.

**Comment by ensonic** [comment]
Hi, this is shown in the about dialog. I am usually sending out a prerelease tarball ~1 month before doing the actual release. I'll add a better comment.

**Comment by josephgbr** [comment]
Thanks. Please consider updating the POT in [translationproject.org](translationproject.org)

**Comment by ensonic** [comment]
The message should actually be translated. But now its a bit late, since the release is out. If you are willing to keep the translations up-to-date it will starting to make sense with the next release.

**Comment by josephgbr** [comment]
Understood. thanks!
