### ISSUE TITLE
Sandbox violation when building on gentoo when introspection is enabled

### ISSUE THREAD

**Issue by simonvanderveldt** [Buzztrax/buzztrax#69]
@ensonic As discussed on IRC previously here the info about the build issue within Gentoo.
(the crash on opening a Machine's property window is fixed! :))

Basically the build is trying to access the ALSA sequencer device, which isn't allowed. If I disable introspection this doesn't happen.

Part of the output:
```
g-ir-scanner: link: ./libtool --mode=link --tag=CC x86_64-pc-linux-gnu-gcc -pthread -o /var/tmp/portage/media-sound/buzztrax-0.10.2/work/buzztrax-0.10.2/tmp-introspectrdFjCX/BuzztraxIc-1.1 -export-dynamic -march=core-avx-i -O2 -pipe -Wl,-O1 -Wl,--as-needed tmp-introspectrdFjCX/var/tmp/portage/media-sound/buzztrax-0.10.2/work/buzztrax-0.10.2/tmp-introspectrdFjCX/BuzztraxIc-1.1.o -L. libbuzztrax-ic.la -lgio-2.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0
libtool: link: x86_64-pc-linux-gnu-gcc -pthread -o /var/tmp/portage/media-sound/buzztrax-0.10.2/work/buzztrax-0.10.2/tmp-introspectrdFjCX/.libs/BuzztraxIc-1.1 -march=core-avx-i -O2 -pipe -Wl,-O1 tmp-introspectrdFjCX/var/tmp/portage/media-sound/buzztrax-0.10.2/work/buzztrax-0.10.2/tmp-introspectrdFjCX/BuzztraxIc-1.1.o -Wl,--export-dynamic -pthread -Wl,--export-dynamic  -Wl,--as-needed -L. ./.libs/libbuzztrax-ic.so -lgio-2.0 -lgmodule-2.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -pthread
No protocol specified
xcb_connection_has_error() returned true
No protocol specified
 * ACCESS DENIED:  open_wr:      /dev/snd/seq
 * ACCESS DENIED:  open_wr:      /dev/snd/seq
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.0.29/work/alsa-lib-1.0.29/src/seq/seq_hw.c:457:(snd_seq_hw_open) open /dev/snd/seq failed: Permission denied
```

I've uploaded my ebuild (Gentoo's package build declaration) to gist https://gist.github.com/simonvanderveldt/18d0cebfef23f53664013c6da398920a

You should be able to compile it using `ebuild buzztrax-9999.ebuild manifest clean merge`

**Comment by ensonic** [comment]
The same probably happens too when you build the gtk-docs, right? I know what happens, but I need to come up with a good way to avoid it. Basically libbuzztrax-ic has gobjects that e.g. discover midi devices or controllers (gamepads). When those discovery modules are created, they start scanning and this causes the sandbox violation.

A quick fix could be to add support for an environment variable, that when it is set it won't scan. Alternatively I can probably add api to explicitly start the scanning from the apps.

**Comment by simonvanderveldt** [comment]
> The same probably happens too when you build the gtk-docs, right?

Hadn't tried that before, but just tried a build with docs enabled and indeed the same thing happens.


> Basically libbuzztrax-ic has gobjects that e.g. discover midi devices or controllers (gamepads). When those discovery modules are created, they start scanning and this causes the sandbox violation.

Does this happen in the constructor/when instantiating them? In that case a separate method to do the scanning sounds like the appropriate fix.

**Comment by ensonic** [comment]
Yep, _constructed() vmethod. I think I've got an idea ...

**Comment by ensonic** [comment]
I hope this fixes it. Please reopen if not and thanks for reporting.

**Comment by simonvanderveldt** [comment]
I'll check if it works this weekend and let you know. Thanks for the quick response!
