### ISSUE TITLE
passing --lib= to autogen.sh doesn't set libdir

### ISSUE THREAD

**Issue by Baggypants** [Buzztrax/buzztrax#71]
According to the wiki http://wiki.buzztrax.org/index.php/Building I should be able to pass --libdir= but it doesn't seem to do anything.

**Comment by ensonic** [comment]
What did you pass as a value? Also "--libdir" is handled by automake, it is unlikely that it won't work.
Why did you change the title to "--lib"? The option is called "--libdir", like said on the wiki or in "configure --help". If you need help with building, it might be easier to chat in irc or https://gitter.im/Buzztrax/buzztrax

**Comment by Baggypants** [comment]
title is a typo. I was trying to build an RPM for fedora, specfile with the issue is here https://gitlab.com/spec-files-for-various-rpms/spec-files-for-various-rpms/commit/fca6eb1c75c933a8c079206f73bbbca7c68fc9fa

in the end I worked around it by using --noconfigure and running the configure with the rpm variables myself. It builds with this now.

**Comment by ensonic** [comment]
you can pass all the variables that you pass to configure also to autogen.sh. But since you got it working, I'll close this.
