### ISSUE TITLE
Use docbook for help instead of scrollkeeper

### ISSUE THREAD

**Issue by plater** [Buzztrax/buzztrax#81]
One of the best features of buzztrax is the help system, unfortunately this uses rarian scrollkeeper compat. Rarian is long gone from Debian and is soon to be dropped from openSUSE. I have to remove rarian from the buzztrax build and this breaks the help system.

**Comment by ensonic** [comment]
Thanks for letting me know. I need to figure whats the migration path. What is the exact error?

**Comment by plater** [comment]
The exact error is that clicking help with no omf files present shows nothing, you need to convert to docbook or html apparently yelp works equally well.

**Comment by ensonic** [comment]
Will follow
https://gitlab.gnome.org/GNOME/totem/commit/59a6bd6064fe7dd047f7b61642aba73e0ba72acf
and switch to
https://wiki.gnome.org/Apps/Yelp/Tools/yelp.m4

**Comment by plater** [comment]
Can confirm that this works perfectly

**Comment by ensonic** [comment]
Thanks! FYI. There is some activity on the project again and we aim to get rid of as many deprecation warning as possible and then make a release.
