### ISSUE TITLE
buzztrax.org down

### ISSUE THREAD

**Issue by eoghanmurray** [Buzztrax/buzztrax#94]
In case this hasn't been flagged!

**Comment by mkesper** [comment]
Last snapshot of the wiki: https://web.archive.org/web/20180512104918/http://wiki.buzztrax.org/index.php/Main_Page

**Comment by ensonic** [comment]
Thanks for letting me know. I am rebuilding a minimal site as a github page:

**Comment by ensonic** [comment]
An old snapshot can be see in the web-archive: https://web.archive.org/web/20200729150728/https://news.buzztrax.org/

The new sites page is super minimal right now. Any content that I should migrate over from the old page? Most of the 'news' are mirrored into the https://github.com/Buzztrax/buzztrax/releases already.

**Comment by trusktr** [comment]
Looks like the build scripts on ArchLinux AUR failed because they tried to request from http://files.buzztrax.org, but I suppose that can easily be replaced with static files on the GitHub site, or even just the release files that GitHub [publishes for each release](https://github.com/Buzztrax/buzztrax/releases).

**Comment by ensonic** [comment]
@trusktr if it is about the source code like "files/releases/buzztrax-0.10.1.tar.gz" then changing that to the github releases would be great. Do you have a link to the ArchLinux AUR build script?

**Comment by ensonic** [comment]
TODO: use something like:
https://dmnfarrell.github.io/software/jekyll-galleries
https://jekyllcodex.org/without-plugin/image-gallery/#
to have a proper gallery. Patches welcome :)

**Comment by ensonic** [comment]
We can always improve the github pages. Closing this for now.
